### ISSUE TITLE
Issues with training

### ISSUE THREAD

**Issue by shapu** [shijieS/SST#43]
Hello,

Thank you for providing open-source code for SST tracker. I am trying to retrain this tracker on MOT17 and I am running into issues. I get this traceback:

Traceback (most recent call last):
  File "train_mot17.py", line 234, in <module>
    train()
  File "train_mot17.py", line 142, in train
    batch_iterator = iter(data_loader)
  File "/home/shashank/anaconda3/envs/SST/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 417, in __iter__
    return DataLoaderIter(self)
  File "/home/shashank/anaconda3/envs/SST/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 242, in __init__
    self._put_indices()
  File "/home/shashank/anaconda3/envs/SST/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 290, in _put_indices
    indices = next(self.sample_iter, None)
  File "/home/shashank/anaconda3/envs/SST/lib/python3.5/site-packages/torch/utils/data/sampler.py", line 119, in __iter__
    for idx in self.sampler:
  File "/home/shashank/anaconda3/envs/SST/lib/python3.5/site-packages/torch/utils/data/sampler.py", line 50, in __iter__
    return iter(torch.randperm(len(self.data_source)).long())
RuntimeError: invalid argument 1: must be strictly positive at /pytorch/torch/lib/TH/generic/THTensorMath.c:2247

I changed the configurations appropriately in the config file before trying to train and I made sure that the dataset paths is configured correctly.

**Comment by shapu** [comment]
I am sorry actually it was my fault. The mot_root was commented in the GTparser of mot.py file. When I uncommented, I am able to train it.
